package com.a9ae0b01f0ffc.VSMSGEN.conf

import com.a9ae0b01f0ffc.commons.implementation.config.T_common_conf

class T_vsms_conf extends T_common_conf{

    static String GC_SMS_CLASSES_CONF
    static String GC_BLACK_BOX_CONFIG
    static String GC_VSMS_RECON_VERSION
    static String GC_VTS_LOG_FILE
    static String GC_FINSIM_CSV_FILE
    static String GC_VTS_CTF_FILE
    static String GC_FINSIM_CTF_FILE
    static String GC_CURRENCY_DECDIGITS_0
    static String GC_CURRENCY_DECDIGITS_3

    T_vsms_conf(String i_conf_file_name) {
        super(i_conf_file_name)
        GC_SMS_CLASSES_CONF = GC_CONST_CONF.GC_SMS_CLASSES_CONF(GC_SMS_CLASSES_CONF)
        GC_BLACK_BOX_CONFIG = GC_CONST_CONF.GC_BLACK_BOX_CONFIG(GC_BLACK_BOX_CONFIG)
        GC_VSMS_RECON_VERSION = GC_CONST_CONF.GC_VSMS_RECON_VERSION(GC_VSMS_RECON_VERSION)
        GC_VTS_LOG_FILE = GC_CONST_CONF.GC_VTS_LOG_FILE(GC_VTS_LOG_FILE)
        GC_FINSIM_CSV_FILE = GC_CONST_CONF.GC_FINSIM_CSV_FILE(GC_FINSIM_CSV_FILE)
        GC_VTS_CTF_FILE = GC_CONST_CONF.GC_VTS_CTF_FILE(GC_VTS_CTF_FILE)
        GC_FINSIM_CTF_FILE = GC_CONST_CONF.GC_FINSIM_CTF_FILE(GC_FINSIM_CTF_FILE)
        GC_CURRENCY_DECDIGITS_0 = GC_CONST_CONF.GC_CURRENCY_DECDIGITS_0(GC_CURRENCY_DECDIGITS_0)
        GC_CURRENCY_DECDIGITS_3 = GC_CONST_CONF.GC_CURRENCY_DECDIGITS_3(GC_CURRENCY_DECDIGITS_3)
    }

}
